### ISSUE TITLE
Support to custom key combination(like ctrl+alt+c) or adding to clipboard with custom menu link 

### ISSUE THREAD

**Issue by piu** [WickyNilliams/react-clipboard#11]
Hi,

I have question that does this module support custom key combination for copying to clipboard(like Ctrl+Alt+C)? Also if there is any support to custom menu implementation like in any react function I want to copy to clipboard dynamically and later paste it on some menu item click.

Is there any example for it? I couldn't find anything of this sought

**Comment by WickyNilliams** [comment]
No, the scope of this component is very limited. It works in the simple cases outlined in the docs, but no more. If you want more complex clipboard handling, I would consider looking elsewhere.
