### ISSUE TITLE
how to handle with copy button ?

### ISSUE THREAD

**Issue by lyquocnam** [WickyNilliams/react-clipboard#7]
Hi author, i see we has a textarea with value, so how user copy from that ?
can i handle a button on side like this demo ?

![image](https://cloud.githubusercontent.com/assets/8347826/17312687/b3c1c178-587e-11e6-8b9b-7db8f36934c9.png)

**Comment by WickyNilliams** [comment]
Unfortunately not. The scope of this component is very narrow. If you want something more advanced I'd consider looking elsewhere
